### ISSUE TITLE
 [FEATURE] Add dbt and DuckDB integration to `hugr-client`

### ISSUE THREAD

**Issue by VGSML** [hugr-lab/hugr-client#2]
# [FEATURE] Add dbt and DuckDB integration to `hugr-client`

## Summary

Extend the `hugr-client` package to support seamless integration with `dbt` and `DuckDB`. This will enable users to query Hugr via GraphQL, register the results as DuckDB tables, use them in dbt models, and clean them up after the pipeline completes — all in a standardized and reusable way.

This feature combines:
- The core Hugr GraphQL client
- DuckDB UDF runtime (e.g. `hugr_exec`, `hugr_clear_all`)
- A custom dbt adapter (`hugr_duckdb`)
- Standard macros (`hugr_query`, `hugr`, `hugr_clear`) usable in any dbt project

---

## Goals

- One-line installation:  

```bash
  pip install hugr-client[dbt]
```

- Plug-and-play integration with dbt:

profiles.yml:

```yaml
outputs:
  dev:
    type: hugr_duckdb
    path: ./project.duckdb
```

packages.yml:

```yaml
outputs:
  dev:
    type: hugr_duckdb
    path: ./project.duckdb
```

- Usage in dbt models:

```jinja
{{ hugr_query("crm_data", "query { crm { customers { id } } }", {}) }}
select * from {{ hugr("crm_data", "crm.customers") }}
{{ hugr_clear("crm_data") }}
```

## Directory Structure

```
hugr-client/
├── hugr/
│   ├── client.py                  # GraphQL + IPC interface
│   ├── duckdb_runtime.py          # hugr_exec, hugr_clear_all, UDF setup
│   ├── dbt_adapter/
│   │   ├── adapters/
│   │   │   └── hugr_duckdb.py     # dbt adapter implementation
│   │   ├── macros/
│   │   │   ├── hugr_query.sql
│   │   │   ├── hugr.sql
│   │   │   └── hugr_clear.sql
│   │   └── dbt_project.yml        # dbt macro package definition
├── pyproject.toml
├── README.md
```

## Technical Tasks

1. DuckDB Runtime
	- hugr_exec(name: str, gql: str, variables: dict)
→ Executes Hugr GraphQL query and registers resulting tables in DuckDB.
	- hugr_clear_all(name: str)
→ Unregisters all tables tied to the query result.
	- register_functions(conn: duckdb.DuckDBPyConnection)
→ Registers UDFs in a given DuckDB session.

2. dbt Adapter
- Create HugrDuckDBAdapter inheriting from DuckDBAdapter
- Create HugrDuckDBConnectionManager and override open() to:
- register Hugr UDFs on session init

3. Macros
- Place hugr_query.sql, hugr.sql, hugr_clear.sql under macros/
- Include dbt_project.yml to define the macro package

4. Setup Integration
- Add entry_points for dbt:

```toml
[project.entry-points."dbt.adapters"]
hugr_duckdb = "hugr-client.dbt_adapter.adapters.hugr_duckdb:HugrDuckDBAdapter"

[project.entry-points."dbt.include"]
dbt_hugr = "hugr-client.dbt_adapter"
```

- Declare optional-dependencies:

```toml
[project.optional-dependencies]
dbt = ["dbt-core", "dbt-duckdb"]
```

## Optional Enhancements

- Allow configuring Hugr endpoint/token via env or profiles.yml
- Support multipart Arrow/Parquet decoding
- Add tracing/logging of Hugr queries and schema resolution
- Export final DuckDB as file and register in Hugr from dbt/CLI

# Outcome

A unified and reusable package hugr_client that supports:

- Low-level Hugr query execution in Python
- dbt workflows using Hugr as a dynamic external source
- DuckDB-based data processing pipelines

This will make hugr-client the canonical bridge between Hugr, modern analytics engineering tools (dbt), and embedded OLAP systems (DuckDB).
